# Generated by Django 5.1 on 2024-08-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("New York", "New York"),
                            ("Los Angeles", "Los Angeles"),
                            ("Chicago", "Chicago"),
                            ("Miami", "Miami"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "departure_time",
                    models.CharField(
                        choices=[
                            ("09:00", "09:00 AM"),
                            ("12:00", "12:00 PM"),
                            ("15:00", "03:00 PM"),
                            ("18:00", "06:00 PM"),
                        ],
                        max_length=5,
                    ),
                ),
                ("passenger_name", models.CharField(max_length=100)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
